PARAMETER_NAMES_RU = {
    # Основные - оба варианта
    "hemoglobin": "Гемоглобин",
    "hgb": "Гемоглобин",
    "hb": "Гемоглобин",
    "erythrocytes": "Эритроциты",
    "rbc": "Эритроциты",
    "leukocytes": "Лейкоциты",
    "wbc": "Лейкоциты",
    "platelets": "Тромбоциты",
    "plt": "Тромбоциты",
    "hematocrit": "Гематокрит",
    "hct": "Гематокрит",
    "esr": "СОЭ",
    "esr_westergren": "СОЭ (Westergren)",
    # Эритроцитарные индексы
    "mcv": "Средний объем эритроцита (MCV)",
    "mch": "Среднее содержание Hb (MCH)",
    "mchc": "Средняя концентрация Hb (MCHC)",
    "rdw_sd": "RDW-SD",
    "rdw_cv": "RDW-CV",
    # Тромбоциты
    "mpv": "Средний объем тромбоцита (MPV)",
    "pct": "Тромбокрит (PCT)",
    "pdw": "PDW",
    # Лейкоформула
    "neutrophils": "Нейтрофилы %",
    "neutrophils_percent": "Нейтрофилы %",
    "neutrophils_percentage": "Нейтрофилы %",
    "neutrophils_absolute": "Нейтрофилы (абс.)",
    "lymphocytes": "Лимфоциты %",
    "lymphocytes_percent": "Лимфоциты %",
    "lymphocytes_percentage": "Лимфоциты %",
    "lymphocytes_absolute": "Лимфоциты (абс.)",
    "monocytes": "Моноциты %",
    "monocytes_percent": "Моноциты %",
    "monocytes_percentage": "Моноциты %",
    "monocytes_absolute": "Моноциты (абс.)",
    "eosinophils": "Эозинофилы %",
    "eosinophils_percent": "Эозинофилы %",
    "eosinophils_percentage": "Эозинофилы %",
    "eosinophils_absolute": "Эозинофилы (абс.)",
    "basophils": "Базофилы %",
    "basophils_percent": "Базофилы %",
    "basophils_percentage": "Базофилы %",
    "basophils_absolute": "Базофилы (абс.)",
    "immature_granulocytes_absolute": "Незрелые гранулоциты (абс.)",
    "immature_granulocytes_percent": "Незрелые гранулоциты %",
    "immature_granulocytes_percentage": "Незрелые гранулоциты %",
    "normoblasts_absolute": "Нормобласты (абс.)",
    "normoblasts_percent": "Нормобласты %",
    "normoblasts_percentage": "Нормобласты %",
    # Гормоны
    "tsh": "ТТГ (тиреотропный гормон)",
    "free_t4": "Свободный Т4",
    "free_t3": "Свободный Т3",
    "testosterone": "Тестостерон",
    "estradiol": "Эстрадиол",
    "prolactin": "Пролактин",
    "cortisol": "Кортизол",
    "lh": "Лютеннизирующий гормон (ЛГ)",
    "fsh": "Фолликулостимулирующий гормон (ФСГ)",
    "shbg": "Глобулин, связывающий половые гормоны (SHBG)",
    "free_androgen_index": "Индекс свободных андрогенов",
    # МАРКЕРЫ ОПУХОЛЕВОГО POCTA
    "psa": "ПСА(простатический специфический АГ)",
    # Липидный профиль Биохимия
    "cholesterol": "Холестерин общий",
    "glucose": "Глюкоза",
    "urea": "Мочевина",
    "total_bilirubin": "Билирубин общий",
    "bilirubin_total": "Билирубин общий",
    "alt": "АЛТ (аланинаминотрансфераза)",
    "ast": "АСТ (аспартатаминотрансфераза)",
    "creatinine": "Креатинин в крови",
    "atherogenic_index": "Индекс атерогенности",
    "gfr_ckd_epi": "Скорость клубочковой фильтрации (СКФ), расчет по формуле CKD-EPI",
}
