# Generated by Django 5.2.6 on 2025-09-28 12:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("medical_analysis", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bloodgeneralanalysis",
            name="medical_data",
        ),
        migrations.DeleteModel(
            name="BloodBiochemAnalysis",
        ),
        migrations.DeleteModel(
            name="BloodGeneralAnalysis",
        ),
    ]
