# Generated by Django 5.2.6 on 2025-09-28 14:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("medical_analysis", "0002_remove_bloodgeneralanalysis_medical_data_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="medicaldata",
            name="session",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="medical_data",
                to="medical_analysis.analysissession",
            ),
        ),
    ]
