# Generated by Django 5.2.7 on 2025-10-02 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_analysis', '0003_alter_medicaldata_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicaldata',
            name='is_confirmed',
            field=models.BooleanField(default=False, help_text='Пользователь подтвердил правильность данных'),
        ),
        migrations.AddField(
            model_name='medicaldata',
            name='laboratory',
            field=models.CharField(blank=True, choices=[('invitro', 'Инвитро'), ('helix', 'Хеликс'), ('kdl', 'КДЛ'), ('gemotest', 'Гемотест'), ('cmd', 'ЦМД'), ('citilab', 'Ситилаб'), ('unknown', 'Неизвестно')], default='unknown', help_text='Лаборатория-источник анализа', max_length=50),
        ),
        migrations.AlterField(
            model_name='analysissession',
            name='analysis_type',
            field=models.CharField(blank=True, choices=[('blood_general', 'Общий анализ крови'), ('blood_biochem', 'Биохимический анализ'), ('hormones', 'Гормональные анализы'), ('other', 'Другие анализы')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='medicaldata',
            name='analysis_type',
            field=models.CharField(choices=[('blood_general', 'Общий анализ крови'), ('blood_biochem', 'Биохимический анализ'), ('hormones', 'Гормональные анализы'), ('other', 'Другие анализы')], max_length=20),
        ),
    ]
