# Generated by Django 5.2.7 on 2025-10-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_analysis', '0004_medicaldata_is_confirmed_medicaldata_laboratory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysissession',
            name='processing_status',
            field=models.CharField(choices=[('uploading', 'Загрузка'), ('processing', 'Обработка'), ('ocr', 'Распознавание текста'), ('parsing', 'Анализ данных'), ('completed', 'Завершено'), ('error', 'Ошибка')], default='uploading', max_length=20),
        ),
    ]
