# Generated by Django 5.2.7 on 2025-10-12 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_analysis', '0005_alter_analysissession_processing_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ParserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpt_enabled', models.BooleanField(default=True, help_text='Включить/выключить парсинг через GPT', verbose_name='Использовать GPT')),
                ('gpt_model', models.CharField(choices=[('gpt-4o-mini', 'GPT-4o Mini (быстрый, дешёвый)'), ('gpt-4o', 'GPT-4o (медленный, дорогой, точный)')], default='gpt-4o-mini', max_length=50, verbose_name='Модель GPT')),
                ('fallback_enabled', models.BooleanField(default=True, help_text='Переключаться на regex при недоступности GPT', verbose_name='Использовать fallback')),
                ('log_gpt_costs', models.BooleanField(default=True, help_text='Записывать стоимость GPT-запросов', verbose_name='Логировать стоимость')),
                ('max_cost_per_request', models.DecimalField(decimal_places=4, default=0.05, help_text='Предупреждение при превышении', max_digits=6, verbose_name='Макс. стоимость запроса ($)')),
                ('max_input_tokens', models.IntegerField(default=8000, verbose_name='Макс. входных токенов')),
                ('max_output_tokens', models.IntegerField(default=2000, verbose_name='Макс. выходных токенов')),
                ('temperature', models.FloatField(default=0.1, help_text='0.0 - детерминированно, 1.0 - креативно', verbose_name='Temperature')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки парсера',
                'verbose_name_plural': 'Настройки парсера',
            },
        ),
    ]
