# Generated by Django 5.2.6 on 2025-10-19 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_analysis', '0006_parsersettings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicaldata',
            name='laboratory',
            field=models.CharField(blank=True, choices=[('invitro', 'Инвитро'), ('helix', 'Хеликс'), ('kdl', 'КДЛ'), ('gemotest', 'Гемотестм'), ('cmd', 'ЦМД'), ('citilab', 'Ситилаб'), ('unknown', 'Неизвестно')], default='unknown', help_text='Лаборатория-источник анализа', max_length=50),
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_type', models.CharField(choices=[('trial', 'триал'), ('paid', 'оплачен')], default='trial', max_length=10)),
                ('upload_limit', models.PositiveIntegerField(default=5)),
                ('used_uploads', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
            },
        ),
    ]
