# Generated by Django 5.2.6 on 2025-10-19 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_analysis', '0007_alter_medicaldata_laboratory_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='subscription_type',
            field=models.CharField(choices=[('trial', 'триал'), ('paid', 'оплачен')], db_index=True, default='trial', max_length=10),
        ),
    ]
